Repository gacheon-sw-academy-2023/Prello, pull requests merged in 2023-01, with the labels that each got.

#2 [PIM-40] 메인 페이지 구현 (테스트 미진행)
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/assets/images/main/facebook.png
  src/assets/images/main/github.png
  src/assets/images/main/instagram.png
  src/assets/images/main/introduce1-temp.png
  src/assets/images/main/introduce2-temp.png
  src/assets/images/main/introduce3-temp.png
  src/assets/images/main/introduce4-temp.png
  src/assets/images/main/linkedIn.png
  src/assets/images/main/logo.png
  src/assets/images/main/main.png
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.styles.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/Footer.types.ts
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/index.css
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/stories/Header.tsx
  src/stories/Page.tsx
  src/stories/header.css
  src/styles/colors.ts
  yarn.lock
Labels: request review

#3 [PIM-29] 로그인 UI 구현
  src/App.tsx
  src/assets/authorization/login/arrow-right.png
  src/assets/authorization/login/cover.png
  src/assets/authorization/login/email.png
  src/assets/authorization/login/padlock.png
  src/assets/authorization/login/profile.png
  src/assets/authorization/pimfy_profile.png
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/login/styles.ts
  src/styles/colors.ts
Labels: request review

#4 [PIM-44] 사이드바 컴포넌트 구현
  .storybook/preview-head.html
  .storybook/preview.cjs
  package.json
  src/App.tsx
  src/assets/main/facebook.png
  src/assets/main/github.png
  src/assets/main/instagram.png
  src/assets/main/introduce1-temp.png
  src/assets/main/introduce2-temp.png
  src/assets/main/introduce3-temp.png
  src/assets/main/introduce4-temp.png
  src/assets/main/linkedIn.png
  src/assets/main/logo.png
  src/assets/main/main.png
  src/assets/workspace/plus-icon.png
  src/assets/workspace/sample-add-icon.png
  src/assets/workspace/sample-profile-image.png
  src/assets/workspace/sample-workspace-image.png
  src/assets/workspace/setting-icon.png
  src/assets/workspace/user-icon.png
  src/components/SideBar/SideBar.stories.tsx
  src/components/SideBar/SideBar.styles.ts
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/SideBar.types.ts
  src/components/SubTitle/SubTitle.stories.tsx
  src/components/SubTitle/SubTitle.styles.ts
  src/components/SubTitle/SubTitle.tsx
  src/components/SubTitle/SubTitle.types.ts
  src/components/WorkspaceImg/WorkspaceImg.stories.tsx
  src/components/WorkspaceImg/WorkspaceImg.styles.ts
  src/components/WorkspaceImg/WorkspaceImg.tsx
  src/components/WorkspaceImg/WorkspaceImg.types.ts
  src/mocks/handlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/login/styles.ts
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  src/pages/workspace/default/index.tsx
  src/pages/workspace/default/styles.ts
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/detail/styles.ts
  src/utils/authorization.ts
  yarn.lock
Labels: request review

#6 [PIM-30] 회원가입 UI 구현
  src/App.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/modal.tsx
  src/pages/authorization/sign-up/modalStyles.ts
  src/pages/authorization/sign-up/styles.ts
Labels: request review

#7 [PIM-35] NotFound 페이지 구현
  src/App.tsx
  src/pages/notFound/index.tsx
  src/pages/notFound/styles.ts
Labels: request review

#8 [PIM-43] 컴포넌트 SubHeader 구현
  .storybook/preview-head.html
  src/components/SubHeader/SubHeader.stories.tsx
  src/components/SubHeader/SubHeader.style.ts
  src/components/SubHeader/SubHeader.tsx
  src/components/SubHeader/SubHeader.types.ts
Labels: request review

#9 [PIM-49] [Netlify] 프론트엔드 배포
  .gitignore
  netlify.toml
  package.json
  vite.config.ts
  yarn.lock
Labels: help wanted, request review

#10 [PIM-33] 보드페이지 UI 구현
  package.json
  public/getMemberData.json
  src/components/SideBar/SideBar.styles.ts
  src/components/SideBar/SideBar.tsx
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  yarn.lock
Labels: request review

#11 [PIM-46] Button 컴포넌트 수정 및 적용
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/login/styles.ts
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/styles.ts
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/page.css
Labels: request review

#12 [PIM-47] 워크스페이스 컴포넌트 구현
  package.json
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/ProfileImg/ProfileImg.stories.tsx
  src/components/ProfileImg/ProfileImg.styles.ts
  src/components/ProfileImg/ProfileImg.tsx
  src/components/ProfileImg/ProfileImg.types.ts
  src/components/SideBar/SideBar.stories.tsx
  src/components/SideBar/SideBar.tsx
  src/components/WorkspaceImg/WorkspaceImg.stories.tsx
  src/components/WorkspaceImg/WorkspaceImg.styles.ts
  src/components/WorkspaceImg/WorkspaceImg.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/default/styles.ts
  src/pages/workspace/detail/index.tsx
  src/utils/mediaQuery.ts
  yarn.lock
Labels: request review

#13 [PIM-54] 보드 페이지 - 드래그 & 드롭 구현
  package.json
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  yarn.lock
Labels: request review

#14 [PIM-53] indexed-db 연결
  src/pages/authorization/login/styles.ts
Labels: request review

#15 [PIM-55] 메인페이지 반응형 구현
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.styles.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/Footer.types.ts
  src/pages/main/default.tsx
  src/pages/main/index.tsx
  src/pages/main/mobile.tsx
  src/pages/main/styles.ts
  src/utils/user.ts
Labels: request review

#17 [PIM-59] 반응형 회원가입 페이지 구현
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/styles.ts
Labels: request review

#18 [PIM-60] 반응형 로그인 화면 구현
  src/pages/authorization/login/index.tsx
  src/pages/authorization/login/styles.ts
Labels: request review

#19 [PIM-64] 회원가입 API 구현
  package.json
  src/App.tsx
  src/mocks/handlers.ts
  src/pages/authorization/sign-up/index.tsx
  yarn.lock
Labels: request review

#20 [PIM-61] 워크스페이스 페이지에 헤더 추가
  src/components/SideBar/SideBar.styles.ts
  src/components/SubHeader/SubHeader.stories.tsx
  src/components/SubHeader/SubHeader.tsx
  src/components/SubHeader/SubHeader.types.ts
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  src/pages/workspace/default/index.tsx
  src/pages/workspace/default/styles.ts
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/detail/styles.ts
Labels: request review

#22 [PIM-62] 로그인 정보 저장하는 recoil 구현
  package.json
  src/App.tsx
  src/pages/authorization/login/index.tsx
  src/pages/workspace/default/index.tsx
  src/utils/atom/user.ts
  src/utils/atom/userSelector.ts
  yarn.lock
Labels: request review

#24 [PIM-66] 워크스페이스 생성 UI 구현
  public/assets/images/main/button.png
  src/App.tsx
  src/pages/workspace/create/index.tsx
  src/pages/workspace/create/styles.ts
  src/pages/workspace/default/index.tsx
  src/routes.ts
Labels: request review

#26 [PIM-68] 리스트 및 아이템 생성/삭제 구현
  src/components/SubHeader/SubHeader.style.ts
  src/pages/board/Board.tsx
  src/pages/board/Tile.tsx
  src/pages/board/index.tsx
  src/pages/board/styles.ts
Labels: request review

#28 [PIM-70] 카드 삭제 및 아이템 전체 삭제 구현
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/DropDownMenu/styles.ts
  src/pages/board/List/List.tsx
  src/pages/board/Tile/Tile.tsx
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  vite.config.ts
Labels: request review

#29 [PIM-74] 모달 컴포넌트 구현
  src/components/InviteModal/InviteModal.tsx
  src/components/InviteModal/InviteModal.types.ts
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modals/CreateModal/CreateModal.style.ts
  src/components/Modals/CreateModal/CreateModal.tsx
  src/components/Modals/DeleteModal/DeleteModal.styles.ts
  src/components/Modals/DeleteModal/DeleteModal.tsx
  src/components/Modals/InviteModal/InviteModal.styles.ts
  src/components/Modals/InviteModal/InviteModal.tsx
  src/components/Modals/SimpleModal/SimpleModal.stories.tsx
  src/components/Modals/SimpleModal/SimpleModal.style.ts
  src/components/Modals/SimpleModal/SimpleModal.tsx
  src/components/Modals/SimpleModal/SimpleModal.types.ts
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/SideBar.types.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/workspace/create/index.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/setting/index.tsx
Labels: request review

#30 [PIM-75] 회원가입 테스트 구현
  src/components/Button/Button.styles.ts
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/mocks/handlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/tests/App.test.tsx
  src/tests/jests/signup/SignUp.test.tsx
Labels: test, request review

#32 [PIM-73] 로그인 API 수정 및 테스트 추가
  src/mocks/handlers.ts
  src/pages/authorization/login/index.tsx
  src/tests/jests/Login/Login.test.tsx
Labels: test, request review
