Repository gacheon-sw-academy-2023/Prello, pull requests merged in 2023-02, with the labels that each got.

#33 [PIM-78] 6주차 피드백 적용
  src/components/Modal/Modal.tsx
  src/components/Modals/CreateModal/CreateModal.tsx
  src/components/Modals/SimpleModal/SimpleModal.tsx
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/modal.tsx
  src/pages/board/List/List.tsx
  src/pages/main/default.tsx
  src/pages/main/mobile.tsx
  src/pages/workspace/default/index.tsx
  src/routes.ts
Labels: refactoring, request review

#34 [PIM-76] 워크스페이스 생성 모킹 구현
  package.json
  src/App.tsx
  src/components/Header/Header.types.ts
  src/components/Modals/CreateModal/CreateModal.tsx
  src/mocks/browsers.ts
  src/mocks/handlers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/main/default.tsx
  src/pages/main/mobile.tsx
  src/pages/workspace/default/index.tsx
  src/recoil/atom/user.ts
  src/recoil/atom/userSelector.ts
  src/utils/dbconfig.ts
  yarn.lock
Labels: feature, request review

#35 [PIM-80] 워크스페이스 생성 에러 핸들링
  src/App.tsx
  src/components/Modals/CreateModal/CreateModal.style.ts
  src/components/Modals/CreateModal/CreateModal.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/setting/styles.ts
  src/recoil/atom/user.ts
  src/utils/dbconfig.ts
Labels: feature, request review

#36 [PIM-79] 워크스페이스 조회 모킹 API 생성
  src/App.tsx
  src/components/Modals/CreateModal/CreateModal.tsx
  src/mocks/workspaceHandlers.ts
  src/pages/workspace/default/index.tsx
  src/pages/workspace/default/styles.ts
Labels: feature, request review

#37 [PIM-77] 카드 목록 CRUD API 구현
  src/components/SideBar/SideBar.styles.ts
  src/mocks/boardHandlers.ts
  src/mocks/browsers.ts
  src/mocks/data/getMemberData.json
  src/pages/board/Card/Card.tsx
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/index.tsx
  src/pages/workspace/default/index.tsx
  src/utils/dbconfig.ts
Labels: request review

#38 [PIM-83] 로그인페이지 로딩 UI 구현
  src/components/CirclularLoading/CircularLoading.styles.ts
  src/components/CirclularLoading/CircularLoading.tsx
  src/mocks/handlers.ts
  src/pages/authorization/login/index.tsx
Labels: UI, request review

#39 [PIM-84] 워크스페이스 스켈레톤 구현 및 오류 해결
  src/mocks/workspaceHandlers.ts
  src/pages/workspace/default/index.tsx
  src/pages/workspace/default/styles.ts
  src/pages/workspace/skeleton/index.tsx
Labels: refactoring, UI, feature, request review

#41 [PIM-85] 보드 생성, 조회 모킹 구현 및 워크스페이스와 연결
  src/App.tsx
  src/mocks/boardHandlers.ts
  src/mocks/browsers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/workspace/default/index.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/detail/skeleton.tsx
  src/pages/workspace/detail/styles.ts
  src/routes.ts
  src/utils/dbconfig.ts
Labels: UI, feature, request review

#40 [PIM-86] 카드 내 아이템 CRUD API 구현
  src/mocks/Board/cardHandlers.ts
  src/mocks/Board/itemHandlers.ts
  src/mocks/boardHandlers.ts
  src/mocks/browsers.ts
  src/pages/board/Card/Card.tsx
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/Item/Item.tsx
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  src/utils/dbconfig.ts
Labels: request review

#42 [PIM-87] 워크스페이스 삭제 Mock API 구현 및 Type 지정
  src/components/Modals/CreateModal/CreateModal.tsx
  src/components/Modals/DeleteModal/DeleteModal.tsx
  src/components/Modals/InviteModal/InviteModal.tsx
  src/mocks/handlers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/board/ItemModal/detail.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/setting/index.tsx
  src/utils/types.ts
Labels: refactoring, feature, request review

#44 [PIM-90] 워크스페이스 삭제/수정 mock API 구현
  src/components/Modals/DeleteModal/DeleteModal.tsx
  src/mocks/workspaceHandlers.ts
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/setting/index.tsx
  src/routes.ts
Labels: feature, request review

#43 [PIM-88] 아이템 상세 페이지 기능 구현
  src/components/Modal/Modal.style.ts
  src/mocks/Board/CardHandlers.ts
  src/mocks/Board/itemHandlers.ts
  src/pages/board/Card/Card.tsx
  src/pages/board/Item/Item.tsx
  src/pages/board/ItemModal/detail.tsx
  src/pages/board/ItemModal/styles.ts
  src/utils/dbconfig.ts
Labels: feature, request review

#45 [PIM-91] 라우팅 설정 및 모달 포탈 리팩토링
  src/components/Header/Header.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalPortal.ts
  src/components/SubHeader/SubHeader.tsx
  src/pages/authorization/login/index.tsx
  src/pages/authorization/login/styles.ts
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/styles.ts
  src/pages/util/index.tsx
Labels: refactoring, feature, request review

#46 [PIM-89] 보드 이름 수정, 삭제 구현
  src/components/BoardItem/BoardItem.styles.ts
  src/components/BoardItem/BoardItem.tsx
  src/components/DropDownMenu/DropDownMenu.styles.ts
  src/components/DropDownMenu/DropDownMenu.tsx
  src/mocks/boardHandlers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/detail/styles.ts
  src/utils/dbconfig.ts
Labels: feature

#47 [PIM-94] 워크스페이스 기능 추가 및 리팩토링
  src/components/BoardItem/BoardItem.styles.ts
  src/components/BoardItem/BoardItem.tsx
  src/components/MobileHeader/MobileHeader.tsx
  src/components/MobileHeader/MobileHeader.types.ts
  src/components/Modals/CreateModal/CreateModal.tsx
  src/components/Modals/InviteModal/InviteModal.tsx
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/SideBar.types.ts
  src/mocks/boardHandlers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/board/index.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/setting/index.tsx
  src/recoil/atom/modal.ts
  src/recoil/atom/modalSelector.ts
  src/recoil/atom/workpsace.ts
  src/recoil/atom/workspaceSelector.ts
  src/routes.ts
  src/utils/types.ts
Labels: refactoring, feature, request review

#49 [PIM-98] 인증 및 보드페이지 e2e test
  cypress.config.ts
  src/mocks/Board/itemHandlers.ts
  src/pages/board/Card/Card.tsx
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/Item/Item.tsx
  src/pages/board/ItemModal/detail.tsx
  src/pages/board/index.tsx
  src/tests/cypress/integration/App/createCard.cy.ts
  src/tests/cypress/integration/App/deleteCard.cy.ts
  src/tests/cypress/integration/App/login.cy.ts
  src/tests/cypress/integration/App/signup.cy.ts
  src/tests/cypress/integration/App/updateCard.cy.ts
Labels: refactoring, test, request review

#50 [PIM-100] 워크스페이스 페이지 ↔️ 보드 페이지 연결
  src/components/Modal/Modal.style.ts
  src/components/SubHeader/SubHeader.tsx
  src/components/SubHeader/SubHeader.types.ts
  src/mocks/Board/CardHandlers.ts
  src/mocks/boardHandlers.ts
  src/pages/board/Card/Card.tsx
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/ItemModal/detail.tsx
  src/pages/board/index.tsx
  src/pages/board/skeleton/index.tsx
  src/utils/dbconfig.ts
Labels: refactoring, UI, feature, request review

#51 [PIM-99] 워크스페이스/보드 생성, 수정, 삭제 E2E 테스트 구현
  src/components/BoardItem/BoardItem.tsx
  src/components/Modals/CreateModal/CreateModal.tsx
  src/components/Modals/DeleteModal/DeleteModal.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/setting/index.tsx
  src/tests/cypress/integration/App/createBoard.cy.ts
  src/tests/cypress/integration/App/createWorkspace.cy.ts
  src/tests/cypress/integration/App/deleteBoard.cy.ts
  src/tests/cypress/integration/App/deleteWorkspace.cy.ts
  src/tests/cypress/integration/App/updateBoard.cy.ts
  src/tests/cypress/integration/App/updateWorkspace.cy.ts
  src/utils/types.ts
Labels: refactoring, test, request review

#54 [PIM-95] API 네이밍 변경, axios interceptor 구현
  src/App.tsx
  src/components/BoardItem/BoardItem.tsx
  src/components/DropDownMenu/DropDownMenu.tsx
  src/components/Modals/CreateModal/CreateModal.tsx
  src/mocks/Board/CardHandlers.ts
  src/mocks/Board/itemHandlers.ts
  src/mocks/boardHandlers.ts
  src/mocks/browsers.ts
  src/mocks/data/getMemberData.json
  src/mocks/userHandlers.ts
  src/mocks/workspaceHandlers.ts
  src/pages/authorization/login/index.tsx
  src/pages/authorization/sign-up/index.tsx
  src/pages/authorization/sign-up/modal.tsx
  src/pages/authorization/sign-up/modalStyles.ts
  src/pages/authorization/sign-up/styles.ts
  src/pages/board/Card/Card.tsx
  src/pages/board/DropDownMenu/dropDownMenu.tsx
  src/pages/board/ItemModal/detail.tsx
  src/pages/board/index.tsx
  src/pages/workspace/default/index.tsx
  src/pages/workspace/detail/index.tsx
  src/pages/workspace/detail/skeleton.tsx
  src/pages/workspace/setting/index.tsx
  src/recoil/atom/modal.ts
  src/recoil/atom/status.ts
  src/recoil/atom/statusSelector.ts
  src/tests/login.test.tsx
  src/utils/api.ts
  src/utils/dbconfig.ts
  src/utils/useAxiosInterceptor.ts
Labels: refactoring, request review

#52 [PIM-101] Code Coverage
  .babelrc
  cypress.config.ts
  nycry.json
  package.json
  src/tests/cypress/integration/App/deleteCard.cy.ts
  src/tests/cypress/integration/App/login.cy.ts
  src/tests/cypress/integration/App/logout.cy.ts
  src/tests/cypress/integration/App/updateCard.cy.ts
  src/tests/cypress/plugins/index.cjs
  vite.config.ts
  yarn.lock
Labels: test, request review

#53 [PIM-102] 보드페이지 카드 스켈레톤 적용 / 보드 수정 및 삭제 오류 해결
  src/components/BoardItem/BoardItem.tsx
  src/components/DropDownMenu/DropDownMenu.tsx
  src/mocks/boardHandlers.ts
  src/pages/board/Card/skeleton.tsx
  src/pages/board/index.tsx
  src/pages/board/styles.ts
  src/pages/workspace/detail/index.tsx
Labels: bug, UI, feature, request review
